sudo: false
services:
  - docker

language: python

env:
  global:
    - DOCKER_IMAGE_NAME=alephdata/memorious

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36

install:
  - "sudo apt-get install p7zip-full"
  - "pip install tox twine"

script:
  - tox

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
      docker build -t $DOCKER_IMAGE_NAME:$TRAVIS_TAG . ;
      docker push $DOCKER_IMAGE_NAME:$TRAVIS_TAG ; else true;
    fi
