matrix:
  include:
  - name: "python tests"
    language: python
    python: "3.6"
    install:
    - "sudo apt-get install p7zip-full libicu-dev"
    - "pip install -q tox twine"
    script:
    - tox
    after_success:
    - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
        python setup.py sdist bdist_wheel ;
        twine upload dist/* ;
      fi
  - name: "docker build"
    services:
    - docker
    script:
    - docker build -t alephdata/memorious . ;
    after_success:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
        docker build -t alephdata/memorious:master . ;
        docker push alephdata/memorious:master ;
      fi
    - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
        docker build -t alephdata/memorious:$TRAVIS_TAG . ;
        docker push alephdata/memorious:$TRAVIS_TAG ;
        docker build -t alephdata/memorious:latest . ;
        docker push alephdata/memorious:latest ;
      fi
    
    
