sudo: false
services:
  - docker

language: python
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

install:
  - "sudo apt-get install p7zip-full libicu-dev"
  - "pip install -q tox twine pyicu"

script:
  - tox

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t alephdata/memorious .
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
      docker tag alephdata/memorious alephdata/memorious:master ;
      docker push alephdata/memorious:master ;
    fi
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
      docker tag alephdata/memorious alephdata/memorious:$TRAVIS_TAG ;
      docker push alephdata/memorious:$TRAVIS_TAG ;
      docker push alephdata/memorious ;
    fi
  
