version: "2"

services:
  postgres:
    image: postgres:9.4
    volumes:
      - "./build/data/postgres:/var/lib/postgresql/data"
      - "./build/logs/postgres:/var/log"
    environment:
      POSTGRES_USER: funes
      POSTGRES_PASSWORD: funes
      POSTGRES_DATABASE: funes

  rabbitmq:
    image: rabbitmq
    volumes:
      - "./build/data/rabbitmq:/var/lib/rabbitmq"
      - "./build/logs/rabbitmq:/var/log"

  app:
    build: .
    command: /bin/bash
    links:
      - postgres
      - rabbitmq
    volumes:
      - "./:/memorious"
      - "./build/logs/app:/var/log"
      - "./build/archive:/data"
      - "/:/host"
    environment:
      MEMORIOUS_DEBUG: "true"
      MEMORIOUS_DATABASE_URI: postgresql://funes:funes@postgres/funes
      MEMORIOUS_CONFIG_PATH: "/crawlers"
      MEMORIOUS_ARCHIVE_TYPE: "file"
      MEMORIOUS_ARCHIVE_PATH: "/data"
      MEMORIOUS_INCREMENTAL: "true"
      MEMORIOUS_HTTP_CACHE: "true"
      MEMORIOUS_BROKER_URI: amqp://guest:guest@rabbitmq:5672
      MEMORIOUS_EAGER: "false"
      ALEPH_HOST: https://data.occrp.org/
    env_file:
      - memorious.env