version: "2"

services:
  postgres:
    image: postgres:9.4
    volumes:
      - "./build/data/postgres:/var/lib/postgresql/data"
      - "./build/logs/postgres:/var/log"
    environment:
      POSTGRES_USER: funes
      POSTGRES_PASSWORD: funes
      POSTGRES_DATABASE: funes

  rabbitmq:
    image: rabbitmq
    volumes:
      - "./build/data/rabbitmq:/var/lib/rabbitmq"
      - "./build/logs/rabbitmq:/var/log"

  worker:
    build: .
    command: celery -A memorious.tasks -B -c 4 -l INFO worker --pidfile /var/lib/celery.pid
    links:
      - postgres
      - rabbitmq
    volumes:
      - "./build/logs/worker:/var/log"
      - "./build/archive:/data"
      - "./build/tmp/worker:/tmp"
    environment:
      MEMORIOUS_DATABASE_URI: postgresql://funes:funes@postgres/funes
      MEMORIOUS_CONFIG_PATH: /crawlers
      MEMORIOUS_INCREMENTAL: "true"
      MEMORIOUS_HTTP_CACHE: "true"
      MEMORIOUS_BROKER_URI: amqp://guest:guest@rabbitmq:5672
    env_file:
      - memorious.env

  beat:
    build: .
    command: celery -A memorious.tasks beat -s /var/lib/celerybeat-schedule.db --pidfile /var/lib/celery.pid
    links:
      - postgres
      - rabbitmq
    volumes:
      - "./build/logs/beat:/var/log"
      - "./build/data/beat:/var/lib/"
      - "./build/archive:/data"
    environment:
      MEMORIOUS_DATABASE_URI: postgresql://funes:funes@postgres/funes
      MEMORIOUS_CONFIG_PATH: /crawlers
      MEMORIOUS_INCREMENTAL: "true"
      MEMORIOUS_HTTP_CACHE: "true"
      MEMORIOUS_BROKER_URI: amqp://guest:guest@rabbitmq:5672
    env_file:
      - memorious.env