name: Test, build and publish Memorious PyPI packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Memorious on Python ${{ matrix.python }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        sudo apt-get install p7zip-full libicu-dev
        pip install tox pyicu twine wheel
        pip install -e '.[dev]'
    - name: Run the tests
      run: |
        pytest --cov=memorious --cov-report term-missing
    - name: Build a distribution
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
