name: memorious docker build

on: [push, create]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Show ref
      run: |
        echo "$GITHUB_REF"
    - name: Build docker image
      run: |
        docker build -t alephdata/memorious:latest .
    - name: Push docker image (master)
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker build -t alephdata/memorious:${GITHUB_SHA} .
        docker push alephdata/memorious:${GITHUB_SHA}
    - name: Get the version
      # id: get_version
      run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Push docker image for tags
      if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags')
      run: |
        docker login -u ${{ secrets.docker_user }} -p ${{ secrets.docker_password }}
        docker build -t alephdata/memorious:${TAG_VERSION} .
        docker push alephdata/memorious:${TAG_VERSION}
        docker push alephdata/memorious:latest